### ISSUE TITLE
Error when making heat map

### ISSUE THREAD

**Issue by marieo254** [hamidghaedi/Enrichment-Analysis#1]
Hi in this part of the code I am getting an error:

### create a new data-frame that has '1' for when a gene is part of a term, and '0' when not
h.dat <- dcast(gene.in.pathway[,c(1,2)], SYMBOL~pathway)
rownames(h.dat) <- h.dat$SYMBOL
h.dat <- h.dat[, -1]
ERROR: Using SYMBOL as value column: use value.var to override.

And when I try to make the heat map it gives me the warning that the data set is not numeric

Kindly can you help me solve the issue

**Comment by hamidghaedi** [comment]
Hi , the error seems to come from `reshape2 `package, to see why this is happenning let take a look at :

`head(gene.in.pathway)`

**Comment by marieo254** [comment]
Thanks for getting back to me Hamid. I run the code and it returned the image attached

<img width="776" alt="Screen Shot 2021-09-16 at 3 45 07 PM" src="https://user-images.githubusercontent.com/90857036/133676314-dca42fa2-77f7-45d7-89e5-e961d38a4e5e.png">

**Comment by hamidghaedi** [comment]
@marieo254 I tired to replicate your error but for me it is worked without error just returned a message (see below) 
```
Using SYMBOL as value column: use value.var to override.
Aggregation function missing: defaulting to length
``` 
See below please for  details :
```
a = c(rep("pathwayA",5), rep("pathwayB",5), rep("pathwayC",5), rep("pathwayD",5))
b = rep(c("geneA", "geneB", "geneC", "geneD"))

df = data.frame(pathway = a, SYMBOL = b)
gene.in.pathway  = as_tibble(df)

head(gene.in.pathway)
# # A tibble: 6 x 2
# pathway  SYMBOL
# <chr>    <chr> 
#   1 pathwayA geneA 
# 2 pathwayA geneB 
# 3 pathwayA geneC 
# 4 pathwayA geneD 
# 5 pathwayA geneA 
# 6 pathwayB geneB 

h.dat <-reshape2::dcast(gene.in.pathway, SYMBOL~pathway)

head(h.dat)
# SYMBOL pathwayA pathwayB pathwayC pathwayD
# 1  geneA        2        1        1        1
# 2  geneB        1        2        1        1
# 3  geneC        1        1        2        1
# 4  geneD        1        1        1        2
```
So your issue should be something related to the your R current environment or packages. Here are  some thoughts: 
- Restart you R session and re-run the analysis, 
- Re-install `reshape2 `package. and re-run the analysis

**Comment by hamidghaedi** [comment]
Error is coming from R env

**Comment by hamidghaedi** [comment]
The error seems to be R env.
